### ISSUE TITLE
Support standalone external ElasticSearch deployment

### ISSUE THREAD

**Issue by elyscape** [openshift/origin-aggregated-logging#100]
Since #60, it is possible to have fluentd send logs to an external ElasticSearch instance in addition to the embedded one. It would be nice to be able to send logs to an external ElasticSearch instance _exclusively_, without even running ElasticSearch (or its associated Kibana and curator) inside OpenShift.

**Comment by ewolinetz** [comment]
Hi, this is possible currently just not out of the box via the deployer.

If you update your Fluentd DC, you can set your *_HOST and *_PORT to be your external ES instance.  If your external ES does not use mutual TLS you can update the *_CLIENT_CERT, *_CLIENT_KEY, *_CA variables to be empty.

If you are using a daemonset for Fluentd you are not able to modify the daemonset directly.  You will need to delete your daemonset, make the appropriate changes to the logging-fluentd-template template and run `oc process logging-fluentd-template | oc create -f -` to recreate the daemonset.

**Comment by elyscape** [comment]
Good to know. Thanks for your help! It might be worthwhile to add some documentation on this to [the log aggregation page](https://docs.openshift.org/latest/install_config/aggregate_logging.html).

**Comment by ewolinetz** [comment]
Opened https://github.com/openshift/openshift-docs/pull/1950 so we can get this information into the docs

**Comment by jcantrill** [comment]
@ewolinetz resolved?

**Comment by ewolinetz** [comment]
Resolved, PR was merged in and new docs have been generated:
https://docs.openshift.org/latest/install_config/aggregate_logging.html#external-elasticsearch-instance-with-fluentd

**Comment by ksemaev** [comment]
Still not clear - what part of role do I need to use for fluentd to send logs to external ELK. Are there any steps for the cluster which I need to perform before setting up FluentD for this?
